name: reflect_buddy
description: A powerful live Dart JSON serializer / deserializer based on reflection
version: 1.0.6
repository: https://github.com/caseyryan/reflect_buddy

environment:
  sdk: ^3.0.1

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  collection: ^1.18.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
